### ISSUE TITLE
Beats Input plugin receiveBufferSize configuration being set from the UI is not taking affect 

### ISSUE THREAD

**Issue by mmayur2016** [Graylog2/graylog-plugin-beats#13] opened 2016-10-06 23:30 UTC
Beats Input plugin receiveBufferSize configuration being set from the UI is not taking affect. I have set the receiveBufferSize to 1048576 from the UI. I am seeing the following message in the logs of the graylog-server.

`2016-10-06 23:19:32,887 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input BeatsInput{title=Beats, type=org.graylog.plugins.beats.BeatsInput, nodeId=null} should be 1048576 but is 124928.`
<img width="1403" alt="screen shot 2016-10-06 at 4 28 49 pm" src="https://cloud.githubusercontent.com/assets/20116953/19174222/00cf8dd8-8be2-11e6-9d25-5f3da021727b.png">

Graylog version - 2.1.1
Beats Plugin version - 1.1.2 

Attaching the screenshot of the configuration for the beats plugin.
I am attaching the screenshot of the configuration being set from the UI.

**Comment by joschi** [comment] 2016-10-07 06:55
Duplicate of Graylog2/graylog2-server#2272.

@mmayur2016 Your operating system has to allow setting higher receive buffer sizes.

**Closed as completed by joschi** 2016-10-07 06:55 UTC
